{{- $chart := "k8s-map-updater" -}}
  {{- $fullName := include (print $chart ".fullname") . -}}
  {{- $labels := include (print $chart ".labels") . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}
  labels:
  {{ $labels | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}
    namespace: {{ .Release.Namespace }}
