{{- $chart := "k8s-map-updater" -}}
  {{- $fullName := include (print $chart ".fullname") . -}}
  {{- $labels := include (print $chart ".labels") . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}
  labels:
  {{ $labels | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "create", "delete", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
