{{- if .Values.ingress.enabled -}}
  {{- $chart := "haproxy" -}}
  {{- $fullName := include (print $chart ".fullname") . -}}
  {{- $labels := include (print $chart ".labels") . -}}
  {{- $kubeVersion := .Capabilities.KubeVersion.GitVersion }}
apiVersion: {{ if semverCompare ">=1.19-0" $kubeVersion }}networking.k8s.io/v1{{ else if semverCompare ">=1.14-0" $kubeVersion -}}networking.k8s.io/v1beta1{{- else -}}extensions/v1beta1{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- $labels | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            {{ if semverCompare ">=1.19-0" $kubeVersion }}
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}"
                port:
                  name: stat
            {{ else }}
            backend:
              serviceName: "{{ $fullName }}"
              servicePort: stat
          {{ end }}
    {{- end }}
  {{- end }}
  {{ with .Values.ingress.tls }}tls: {{- toYaml . | nindent 4 }}{{- end }}
  {{- end -}}
